#!/bin/bash

function PrintHelp {
   echo " "
   echo "USAGE: 'launchSNAFU nproc que' "
   exit 1
}
                              
name="snafu"
        
nproc=$1
echo $nproc

if ! [[ $nproc =~ ^[1-9]+$ ]] ; then
   echo "error: Nproc is not an integer number" 
   PrintHelp
fi

#which queue
cluster=$(uname -a | awk {'print $2'})
if [[ ! -n "$3" ]]; then
if [ "$cluster" = "as67-1" ]; then
   queue='sq-8-16'
elif [ "$cluster" == "403-a324-01" ]; then
   queue='aq'
elif [ "$cluster" = "403-as67-01" ]; then
   queue='nq'
fi
else 
queue=$2
fi

cat > r.$name << EOF
#!/bin/bash

#$ -V
#$ -cwd
#$ -e .
#$ -o .
#$ -pe shm $nproc 
#$ -notify

export OMP_NUM_THREADS=1
SNAFUS $input
EOF

echo "Launching SNAFU job for $input using $nproc processors."
echo "Results will be saved to $name.out, JOB information in $name.log"
echo "qsub -cwd -V -q $queue -pe shm $nproc r.$name"
echo "-----------------------------------------"
qsub -cwd -V -q $queue -pe shm $nproc  r.$name
