#!/bin/bash

#$ -cwd -V
OUTFILE="snafu.out"

export SCRDIR="/scratch/$USER/SNAFU-${JOB_ID}"
export PATH="/home/chalabaj/prog/Anaconda3-5.1.0-Linux-x86_64/bin:$PATH"
export SNAFUDIR="/home/chalabaj/snafu"
export basedir=$PWD
export OMP_NUM_THREADS=1

jobfile=job.log
delscratch="true"

echo "NODE  ${HOSTNAME}"     >  $jobfile
echo "SCRATCH  ${SCRDIR}"    >>  $jobfile
echo  $basedir               >>  $jobfile
echo 'NSLOTS: '${NSLOTS}     >>  $jobfile   #NSLOTS

if [[ -d $SCRDIR ]];then
   echo "Job direcory $SCRDIR already exist!"
   echo "Exiting..."
   exit 1
else
   mkdir ${SCRDIR}
fi

cp -r $SNAFUDIR/* $SCRDIR/.
cp -r $basedir/* $SCRDIR/.

cd $SCRDIR
 
function clean_scratch {
   cp -pr * $basedir/.
   if [[ $? -ne "0" ]];then
      echo "Error when copying the data from scratch back to the server."
      echo "I will keep the directory $SCRATCH on node ${HOSTNAME}"
      exit 1
   fi
   if [[ $delscratch -eq "true" ]];then
      cd ../
      rm -r $SCRDIR
   fi
   exit 1
}
trap clean_scratch SIGUSR2  #if qdel JOBID then copy current data to basedir


python snafy.py > $OUTFILE

cp -r $SCRDIR/* $basedir

echo 'Normal termination of:' ${JOB_ID} >> $jobfile
clean_scratch
