#!/bin/bash
# Launching script for SNAFU code
# Written for SGE queuing system
# The queue part should be modified for your node names
# Resulting file r.$name should be modified if one uses diferent queuing system

function PrintHelp {
   echo " "
   echo "USAGE: 'launchSNAFU nproc que ' "
   echo "USAGE: 'launchSNAFU nproc que tera' for SNAFU+TERACHEM"
   exit 1
}
                              
name="snafu"
        
nproc=$1


if ! [[ $nproc =~ ^[1-9]+$ ]] ; then
    echo "ERROR: Nproc is not an integer." 
    PrintHelp
fi

if [[ $# -lt 2 ]];then
    echo "ERROR: Wrong number of parameters."
    PrintHelp
fi

if [[ ! -f input.in ]];then
    echo "ERROR: input.in not found. Exiting."
    exit 1
fi
if [[ ! -f geom.in ]];then
    echo "ERROR: geom.in not found.  Exiting."
    exit 1
fi
# WHICH QUEUE:
queue=$2

# FILE SUBMITTED TO QUE (SGE-like)
if [[ $# -eq 3 ]] || [[ $3 == "tera" ]];then
  
  if [[ ! -f ABINITIO/tera.inp ]];then
  echo "ERROR: tera.inp not found"
  exit 1
  else

  cat > r.$name << EOF
#!/bin/bash
  
#$ -V
#$ -cwd
#$ -pe shm 1 
#$ -notify
#$ -l num_gpu=1
TERASNAFUS $input
EOF
  fi
else
cat > r.$name << EOF
#!/bin/bash

#$ -V
#$ -cwd
#$ -pe shm $nproc 
#$ -notify
SNAFUS $input
EOF
fi
echo " "
echo "    __________   _________    _____ _   _____    ________  __   ____  _____  __";
echo "   /  _/_  __/  /  _/ ___/   / ___// | / /   |  / ____/ / / /  / __ \/   \ \/ /";
echo "   / /  / /     / / \__ \    \__ \/  |/ / /| | / /_  / / / /  / / / / /| |\  / ";
echo " _/ /  / /    _/ / ___/ /   ___/ / /|  / ___ |/ __/ / /_/ /  / /_/ / ___ |/ /  ";
echo "/___/ /_/    /___//____/   /____/_/ |_/_/  |_/_/    \____/  /_____/_/  |_/_/   ";
echo " ";
echo "_____________________________________________________________________________ ";
echo "Launching SNAFU job for $input using $nproc processors."
echo "Results will be saved to $name.out, job.log can be used to fetchabin.sh data."
echo "qsub -cwd -V -q $queue -pe shm $nproc r.$name"
qsub -q $queue r.$name
echo "_____________________________________________________________________________ ";


