#!/bin/bash
# Launching script for SNAFU code
# Written for SGE queuing system
# The queue part should be modified for your node names
# Resulting file r.$name should be modified if one uses diferent queuing system

function PrintHelp {
   echo " "
   echo "USAGE: 'launchSNAFU nproc que ' "
   echo "USAGE: 'launchSNAFU nproc que tera' for SNAFU+TERACHEM"
   exit 1
}
                              
name="snafu"
        
nproc=$1
echo $nproc

if ! [[ $nproc =~ ^[1-9]+$ ]] ; then
   echo "error: Nproc is not an integer number" 
   PrintHelp
fi

if [[ $# -lt 2 ]];then
echo "Wrong number of parameters: <2"
fi

# WHICH QUEUE:
queue=$2

# FILE SUBMITTED TO QUE (SGE-like)
if [[ $# -eq 3 ]] || [[ $3 == "tera" ]];then
  if [[ ! -f ABINITIO/tera.inp ]];then
  echo "tera.inp not found"
  exit 1
  else
  cat > r.$name << EOF
#!/bin/bash
  
#$ -V
#$ -cwd
#$ -pe shm 1 
#$ -notify
#$ -l num_gpu=1
TERASNAFUS $input
EOF
  fi
else
cat > r.$name << EOF
#!/bin/bash

#$ -V
#$ -cwd
#$ -pe shm $nproc 
#$ -notify
SNAFUS $input
EOF
fi

echo "   SSSSSSSSSSSSSSS NNNNNNNN        NNNNNNNN               AAA               FFFFFFFFFFFFFFFFFFFFFFUUUUUUUU     UUUUUUUU";
echo " SS:::::::::::::::SN:::::::N       N::::::N              A:::A              F::::::::::::::::::::FU::::::U     U::::::U";
echo "S:::::SSSSSS::::::SN::::::::N      N::::::N             A:::::A             F::::::::::::::::::::FU::::::U     U::::::U";
echo "S:::::S     SSSSSSSN:::::::::N     N::::::N            A:::::::A            FF::::::FFFFFFFFF::::FUU:::::U     U:::::UU";
echo "S:::::S            N::::::::::N    N::::::N           A:::::::::A             F:::::F       FFFFFF U:::::U     U:::::U ";
echo "S:::::S            N:::::::::::N   N::::::N          A:::::A:::::A            F:::::F              U:::::D     D:::::U ";
echo " S::::SSSS         N:::::::N::::N  N::::::N         A:::::A A:::::A           F::::::FFFFFFFFFF    U:::::D     D:::::U ";
echo "  SS::::::SSSSS    N::::::N N::::N N::::::N        A:::::A   A:::::A          F:::::::::::::::F    U:::::D     D:::::U ";
echo "    SSS::::::::SS  N::::::N  N::::N:::::::N       A:::::A     A:::::A         F:::::::::::::::F    U:::::D     D:::::U ";
echo "       SSSSSS::::S N::::::N   N:::::::::::N      A:::::AAAAAAAAA:::::A        F::::::FFFFFFFFFF    U:::::D     D:::::U ";
echo "            S:::::SN::::::N    N::::::::::N     A:::::::::::::::::::::A       F:::::F              U:::::D     D:::::U ";
echo "            S:::::SN::::::N     N:::::::::N    A:::::AAAAAAAAAAAAA:::::A      F:::::F              U::::::U   U::::::U ";
echo "SSSSSSS     S:::::SN::::::N      N::::::::N   A:::::A             A:::::A   FF:::::::FF            U:::::::UUU:::::::U ";
echo "S::::::SSSSSS:::::SN::::::N       N:::::::N  A:::::A               A:::::A  F::::::::FF             UU:::::::::::::UU  ";
echo "S:::::::::::::::SS N::::::N        N::::::N A:::::A                 A:::::A F::::::::FF               UU:::::::::UU    ";
echo " SSSSSSSSSSSSSSS   NNNNNNNN         NNNNNNNAAAAAAA                   AAAAAAAFFFFFFFFFFF                 UUUUUUUUU      "

echo "Launching SNAFU job for $input using $nproc processors."
echo "Results will be saved to $name.out, JOB information in $name.log"
echo "qsub -cwd -V -q $queue -pe shm $nproc r.$name"
echo "-----------------------------------------"
qsub -q $queue r.$name
